### ISSUE TITLE
Add ELK Stack to observatory installation

### ISSUE THREAD

**Issue by rhosking** [The-Academic-Observatory/observatory-platform#177]
Elasticsearch and Kibana provide an interesting set of capabilities for the observatory platform. Both for building API based services using the capabilities of Elasticsearch and for building dashboards using Kibana.

The following scope of work is proposed to integrate these features in a local development environment as a first step:
- [ ] Review options for running Elasticsearch and Kibana via docker (version 7.8): https://www.elastic.co/guide/en/elastic-stack-get-started/master/get-started-docker.html
- [ ] Extend the cli to handle starting and stopping ES and Kibana https://github.com/The-Academic-Observatory/academic-observatory/blob/develop/academic_observatory/cli/observatory.py
- - [ ] Create a new @cli.command + method 'def service():' largely following the existing 'platform():' example
- - [ ] Extend the configuration to hold values for ES + Kibana https://github.com/The-Academic-Observatory/academic-observatory/blob/develop/academic_observatory/utils/config_utils.py
- - [ ] Develop tests for new configuration and methods for starting ES and Kibana
- - [ ] Consider how / where we can save dashboards, searches and other Kibana/ES state https://www.elastic.co/guide/en/kibana/current/managing-saved-objects.html

**Comment by rhosking** [comment]
@jdddog how much of this will be addressed in your open Pull request? Might need a few of these points to be split out into individual issues if they are not going to make the initial version

**Comment by jdddog** [comment]
Probably most of them.

> Review options for running Elasticsearch and Kibana via docker (version 7.8): https://www.elastic.co/guide/en/elastic-stack-get-started/master/get-started-docker.html

This part is done in Docker Compose here: https://github.com/The-Academic-Observatory/observatory-platform/blob/feature-elastic/docker-compose.observatory.yml#L96-L115. There is one docker container for Elasticsearch and one for Kibana.

> Extend the cli to handle starting and stopping ES and Kibana https://github.com/The-Academic-Observatory/academic-observatory/blob/develop/academic_observatory/cli/observatory.py
>  Create a new @cli.command + method 'def service():' largely following the existing 'platform():' example
>  Extend the configuration to hold values for ES + Kibana https://github.com/The-Academic-Observatory/academic-observatory/blob/develop/academic_observatory/utils/config_utils.py
>  Develop tests for new configuration and methods for starting ES and Kibana

I have it setup so that Elasticsearch and Kibana are start and stop when the platform starts and stops, e.g. `observatory platform start` and `observatory platform stop`.

>  Consider how / where we can save dashboards, searches and other Kibana/ES state https://www.elastic.co/guide/en/kibana/current/managing-saved-objects.html

I currently map the Elasticsearch data folder to a volume, which saves the data on the host machine. I need to check that everything from Kibana is persisted by doing this, but I think it is.
