### ISSUE TITLE
Prototype Elasticsearch Powered API - Use case is to power reporting library

### ISSUE THREAD

**Issue by rhosking** [The-Academic-Observatory/observatory-platform#331]
Making reference to the broader set of work that is being defined around building a set of platform APIs for managing the broader observatory operations #35 #34 #33 

The goals is to prove out the various components for providing the data for the reporting library via a REST API, powered by Elasticsearch. The following are suggested steps, focused as much around learning the various pieces of technology as they are about building a working system.

- [x] Using the Kibana Dev Console (https://www.elastic.co/guide/en/kibana/current/devtools-kibana.html) build out a range of initial queries that will fetch the required data from Elasticsearch Indexes. The following is an initial list of the types of data, each could be applicable to any of the aggregated entities we have (institutions, countries, regions, etc):
 - - [x]  Fetching metrics (total_outputs, counts for open access types etc), based on a set of id's a year ranges
 - - [x]  Fetching output types, and their statues, also based on a set of IDs and year ranges
 - - [x]  Fetching Collaboration information, also based on a set of IDs and year ranges
 - - [x]  Publisher Information, based on IDs and years
 - - [x]  Journals Information, based on IDs and years
 - - [x]  Funder information, based on IDs and years
 - - [x]  Citation Information, based on IDs and years
- [x] Wrap up each of these queries within a jinja2 template, creating python methods that are able to accept the set of required parameters to build the final queries. These parameters will be, but not limited too, the aggregated entity, id or list of ids, year or range of years
- [x] Wrap these parameterised queries up using the Elasticsearch python client, and create method(s) that wrap the above logic and which return useful JSON/PythonObjects.
- [x] Consider the options for wrapping the above into a Flask/OpenAPI interface and options for deploying potentially on Cloud run as an initial target

There will be a range of other queries, that will perform comparisons that are not yet captured. As this work progresses @cameronneylon will be able to provide input on additional sources of data he requires. @jdddog would be good to get your eyes on this too. Especially the last couple of points, as how we structure all of that work is TBD

**Comment by rhosking** [comment]
Much of the existing data flows into the reporting analysis are defined via SQL statements found here: https://github.com/The-Academic-Observatory/observatory-platform/blob/develop/observatory-reports/observatory/reports/tables.py

**Comment by aroelo** [comment]
Most of these points have been implemented. The current state is an flask app using connexion & openapi2.0.
I first tried deploying it on google cloud run manually and later tried out 'waypoint' to deploy to google cloud run.

I'm working together with @cameronneylon to find out the best way to make this API work with the reports as well as optimising the schema / filtering parameters. See https://github.com/The-Academic-Observatory/observatory-platform/issues/343 for schema changes.

Some additional points that came to mind while developing:
* I'm currently using the elasticsearch python client, this works quite well and takes away the need of wrapping up queries in a jinja2 template. The queries can be made as a dictionary instead.
I wonder if there would be an advantage of eliminating the elasticsearch python client, and just use python 'requests' instead. I think the elasticsearch python client is easier to use, but it adds an additional dependency.
* Do we want to use some form of authentication or is the API publicly available?
* In elasticsearch, will we use aliases to refer to the 'latest' index? For now I'm using the indexes of '20201205' in the staging environment, because this date seems to be the most complete. But the date is hardcoded in the index name. It would be great if I can always refer to e.g. 'citations-author' instead of 'citations-author-20201205'

**Comment by aroelo** [comment]
Preferably the expected schema of the relevant query is returned as well, I found the elasticsearch mappings on github [here](https://github.com/The-Academic-Observatory/academic-observatory/tree/develop/academic-observatory-dags/academic_observatory/dags/database/schema), so hopefully we can just link to these and parse them so they return a json schema.
The only challenge might be getting these files in the docker image.

**Comment by cameronneylon** [comment]
Is there a place where an external user can check which subsets are availability for which aggregations? I get a 503 when I query group-funders, presumably because that table doesn't exist in ES?

Not sure what the expected behavior should be (404? Empty result? 204 doesn't seem right) but the current behavior is confusing on the user end.

**Comment by aroelo** [comment]
> Is there a place where an external user can check which subsets are availability for which aggregations? I get a 503 when I query group-funders, presumably because that table doesn't exist in ES?
> 
> Not sure what the expected behavior should be (404? Empty result? 204 doesn't seem right) but the current behavior is confusing on the user end.

I suspect the error was created by something else, I tried group-funders and this works for me:
https://waypoint-elasticsearch-app-qjb5mfja7a-ue.a.run.app/query?agg=group&subset=funders&limit=2

```
{
  "returned_hits": 2,
  "total_hits": 438768,
  "schema": {
    "schema": "to_be_created"
  },
  "hits": [
    {
      "_index": "funders-group-20201205",
      "_type": "_doc",
      "_id": "PenmQHYBGinIh2YA4dEP",
      "_score": 1.0,
      "id": "au_run",
      "name": "Regional Universities Network",
      "country": null,
      "country_code": "AU",
      "region": null,
      "subregion": null,
      "coordinates": null,
      "published_year": "2018-12-31",
      "funder_name": "National Science Foundation for Young Scientists of China",
      "funder_country": null,
      "funder_country_code": null,
      "funder_type": null,
      "funder_sub_type": null,
      "total_outputs": 1,
      "num_oa_outputs": 1,
      "num_green_outputs": 1,
      "num_gold_outputs": 1
    },
    {
      "_index": "funders-group-20201205",
      "_type": "_doc",
      "_id": "PunmQHYBGinIh2YA4dEP",
      "_score": 1.0,
      "id": "au_run",
      "name": "Regional Universities Network",
      "country": null,
      "country_code": "AU",
      "region": null,
      "subregion": null,
      "coordinates": null,
      "published_year": "2018-12-31",
      "funder_name": "Hort Innovation Australia",
      "funder_country": null,
      "funder_country_code": null,
      "funder_type": null,
      "funder_sub_type": null,
      "total_outputs": 1,
      "num_oa_outputs": 0,
      "num_green_outputs": 0,
      "num_gold_outputs": 0
    }
  ]
}
```
These are the possible aggregations:
- author
- country
- funder
- group
- institution
- publisher

And the subsets are:
- citations
- collaborations
- disciplines
- events
- funders
- journals
- oa-metrics
- output-types
- publishers

In general, all combinations of aggregations/subsets should work, with the exception of publisher-collaborations.
That gives an error like this:
```
{
  "type": "about:blank",
  "title": "Internal Server Error",
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500
}
```

I'm not sure if this index/combination is missing on purpose or if this is an error and it should be created in elasticsearch.

**Comment by aroelo** [comment]
Latest update:

* The API usage requires a key, either in the query or in the header. For now there are 3 API keys, stored in a local file. They were created manually using the built-in python 'secrets' library and then using `secrets.token_hex(16)`.

*  The response includes a schema, but the actual schema is empty for now. 

* The number of results returned is limited to 10.000. If there are more results than that, you need to loop over the results, something like this (the API key is fake):
```
import json
import requests
url = 'http://https://waypoint-elasticsearch-app-qjb5mfja7a-ue.a.run.app/query?agg=institution&subset=journals&id=grid.4691.a,grid.469280.1&from=2019&to=2020&api_key=158f9f48b674b0fdd18e5b465d7ae37e'
response = requests.get(url).json()
results = response['results']
scroll_id = response['scroll_id']
all_results = results
while results:
    new_url = url+'&scroll_id='+scroll_id
    response = requests.get(url).json()
    results = response['results']
    scroll_id = response['scroll_id']
    all_results += results
```

* If you would like to return less than 10.000 results, you can set a limit that is between 0 & 10.000

**Comment by cameronneylon** [comment]
There is a working version of the tables that I am currently using that pulls data exclusively from the API now available on commit f005472 in the branch cn-es-api. This is used in a version of the reports that provides country and institution reports. 

Expanding to group reports will require some additional tables to be ported to ES, specifically some version of the groupings table. Funders will require further work

**Comment by cameronneylon** [comment]
Depending on when we loop back around on this, it would be useful up at the `schema` level or in that general first layer of metadata to have a starting point on a provenance chain. We've got the name of the index the data is drawn from already. It would be good to add to that a record of which upstream raw data dumps were used/state of the input data and which run of the overall workflow this represents. That would be good to incorporate into reports and also useful for dashboards.

**Comment by aroelo** [comment]
Background info on deploying API.

**Google Cloud Preparation**
- I followed [this quickstart guide](https://cloud.google.com/run/docs/quickstarts/build-and-deploy#python) to get going, see the 'before you begin' steps here to check steps related to using Cloud Run in general. 
- Set project ID, e.g. for me 'workflows-dev'
`export PROJECT_ID=workflows-dev`
- Install the berglas client, see https://github.com/GoogleCloudPlatform/berglas
- Create secrets related to elasticsearch username, password and address/url and give access to service account
I'm using the Compute Engine default service account, because this is used by 'Waypoint'. Waypoint does have the option to specify a service account in their latest release, but this is not working for me for now. 
```
berglas create sm://${PROJECT_ID}/es_password "xx"
berglas create sm://${PROJECT_ID}/es_username "xx"
berglas create sm://${PROJECT_ID}/es_url "xx"

berglas grant sm://${PROJECT_ID}/es_password --member serviceAccount:xxxxxx-compute@developer.gserviceaccount.com
berglas grant sm://${PROJECT_ID}/es_url --member serviceAccount:xxxxxxx-compute@developer.gserviceaccount.com
berglas grant sm://${PROJECT_ID}/es_username --member serviceAccount:xxxxxx-compute@developer.gserviceaccount.com
```

- Create API keys, store file locally, see image (the keys are fake)
   -  Create a file called 'elasticsearch_auth.txt' at `academic_observatory/observatory-platform/observatory-platform/observatory/platform/elasticsearch/app/api/elasticsearch_auth.txt`
   -  Add username and key, separated by a space. The username is not really used atm.
   - I used this to create the key:
```
import secrets
secrets.token_hex(16)
```
![image](https://user-images.githubusercontent.com/22207600/106109289-5421a300-6184-11eb-834c-2687ff049f25.png)
 
**Using Cloud Run manually**
- Build the image:
`gcloud builds submit --tag gcr.io/${PROJECT_ID}/elasticsearch-api`

- Deploy the image:
`gcloud run deploy --image gcr.io/${PROJECT_ID}/elasticsearch-api --platform managed`
    -  Press enter when prompted for the service name
    -  Pick a region (I used us-central1, but surely other regions will work as well)
    -  Allow unauthenticated invocations

**Using Waypoint**
- Install waypoint 0.1.5, the latest version 0.2.0 gives an error (https://github.com/hashicorp/waypoint/issues/917).
See https://learn.hashicorp.com/tutorials/waypoint/get-started-install for installation, since it is not the latest release, manual might be easiest, downloads can be found here: https://www.waypointproject.io/downloads
- Authenticate to Google Cloud if that has not been setup yet, see [waypoint instructions](https://learn.hashicorp.com/tutorials/waypoint/google-cloud-run?in=waypoint/deploy-google-cloud#authenticate-to-google-cloud)
- Install Waypoint server (local), see [waypoint instructions](https://learn.hashicorp.com/tutorials/waypoint/google-cloud-run?in=waypoint/deploy-google-cloud#install-the-waypoint-server)
- Enter the elasticsearch directory at `academic_observatory/observatory-platform/observatory-platform/observatory/platform/elasticsearch`
- Run `waypoint init`
- Run `waypoint up`, use the 'Release URL', the 'Deployment URL' is not always working for me.
- Run `waypoint destroy`

**Additional note**
I have added some tests in the `academic_observatory/observatory-platform/observatory-platform/observatory/platform/elasticsearch/app/test_query.py` file. They are not complete yet, but perhaps they help to understand the code.

@jdddog Please let me know if you have any more questions

**Comment by aroelo** [comment]
Feature requests (if this list increases, might make sense to open a new dedicated issue):

- [ ] Include the date of the index which is used to retrieve data in the API output (by default the alias is used, so this points to the latest index).
- [ ] Add an optional field that can explicitly select a desired index (instead of the alias/latest).
